version: '3'  # version of compose format 

services:
  laptop-service:
    build: ./laptop
    volumes:
      - .:/todo
    ports:
      - "5000:5000"
    environment:
      - DB_PORT_27017_TCP_ADDR=db
    depends_on:
      - db
  db:
    image: mongo:3.6
    ports:
      - "27017:27017"

  website:
    image: php:apache  
    volumes:
      - ./website:/var/www/html 
    ports:
      - 5002:80  # host:container
    depends_on:
      - laptop-service  # website is not going to work unless laptop-service is running
